// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgnhoeiaknzpkanzikmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnbmhvZWlha256cGthbnppa211Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NzcxNzQsImV4cCI6MjA3NzU1MzE3NH0.dFE1QAkXw06rwKIpU6ykqSBXHlgOpSVjnrcwsiGHqvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});